version: 2.1

jobs:
  build:
    working_directory: ~/
    docker:
      - image: cimg/node:19.1.0
    steps:
      - checkout:
        path: ~/
      - run: npm install 
      - run: PORT=0 npm test 
  